import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    title: "Create Next App",
    description: "Generated by create next app",
    images: [
      {
        url: "https://example.com/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "Og Image Alt",
      },
    ],
  },
};

export default function NotFound() {
  return (
    <div className="app app-404-page">
      <div className="container mb-5">
        <div className="row">
          <div className="col-12 col-md-11 col-lg-7 col-xl-6 mx-auto">
            <div className="app-card p-5 text-center shadow-sm">
              <h1 className="page-title mb-4">404<br /><span className="font-weight-light">Page Not Found</span></h1>
              <div className="mb-4">
                Sorry, we can't find the page you're looking for.
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}